#define MIN_TO_MS(MIN) (MIN * 60 * 60 * 1000)
#define DEVICE_ON_BATTERY_MEASUREMENT_INTERVAL_MIN (30)
#define DEVICE_OFF_BATTERY_MEASUREMENT_INTERVAL_MIN (15)
#define DEVICE_ON_BATTERY_MEASUREMENT_INTERVAL_MS (MIN_TO_MS(DEVICE_ON_BATTERY_MEASUREMENT_INTERVAL_MIN))
